<dec f='include/c++/10/stdexcept' l='226' type='void std::runtime_error::runtime_error(const std::string &amp; __arg)'/>
<use f='include/c++/10/system_error' l='435' u='c' c='_ZNSt12system_errorC1ESt10error_code'/>
<use f='include/c++/10/system_error' l='438' u='c' c='_ZNSt12system_errorC1ESt10error_codeRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='include/c++/10/system_error' l='441' u='c' c='_ZNSt12system_errorC1ESt10error_codePKc'/>
<use f='include/c++/10/system_error' l='447' u='c' c='_ZNSt12system_errorC1EiRKNSt3_V214error_categoryE'/>
<use f='include/c++/10/system_error' l='451' u='c' c='_ZNSt12system_errorC1EiRKNSt3_V214error_categoryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<doc f='include/c++/10/stdexcept' l='224'>/** Takes a character string describing the error.  */</doc>
<use f='qv2ray/test/catch.hpp' l='10500' u='c' c='_ZN5Catch19throw_runtime_errorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
