<def f='include/c++/10/bits/exception_ptr.h' l='102' ll='104' type='void std::__exception_ptr::exception_ptr::exception_ptr(std::nullptr_t )'/>
<use f='include/c++/10/future' l='721' u='c' c='_ZNKSt14__basic_future13_M_get_resultEv'/>
<use f='qv2ray/test/catch.hpp' l='10662' u='c' c='_ZNK5Catch27ExceptionTranslatorRegistry24translateActiveExceptionB5cxx11Ev'/>
