<dec f='qv2ray/test/catch.hpp' l='2987' type='std::string Catch::translateActiveException()'/>
<use f='qv2ray/test/catch.hpp' l='8249' u='c' c='_ZN5Catch16AssertionHandler33handleUnexpectedInflightExceptionEv'/>
<use f='qv2ray/test/catch.hpp' l='8382' u='c' c='_ZN5Catch24handleExceptionMatchExprERNS_16AssertionHandlerERKNS_8Matchers4Impl11MatcherBaseINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERKNS_9StringRefE'/>
<def f='qv2ray/test/catch.hpp' l='12419' ll='12421' type='std::string Catch::translateActiveException()'/>
<use f='qv2ray/test/catch.hpp' l='12830' u='c' c='_ZN5Catch10RunContext14runCurrentTestERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_'/>
