<def f='include/c++/10/exception' l='53' type='void std::bad_exception::bad_exception()'/>
